### ISSUE TITLE
Use Docker images for CI?

### ISSUE THREAD

**Issue by daewok** [cl-plus-ssl/cl-plus-ssl#121]
I noticed that CI is still broken. I've been working with the CLF on building out a set of Docker images <https://common-lisp.net/project/cl-docker-images/> with one use case being CI. If you're interested I could look at using those images to run the jobs on Travis, Github, or something else (Github Actions would probably be my preference as I've been toying with the idea of making an Action for CL testing).

There are images for every implementation currently tested except Allegro and I'm currently evaluating the options for supporting that.

One big benefit of using images instead of the current setup is that the images have the implementation already built inside it, so you don't waste CI minutes on compiling it.

**Comment by avodonosov** [comment]
Hi @daewok, thank you for the suggestion.

I actually found a solution for CI already, and finished it just now, this build is going to pass https://travis-ci.org/github/cl-plus-ssl/cl-plus-ssl/builds/761858930

Still, I'd be interesting to discuss how could that work, in particular regarding keeping up to date with latest lisp implementations and Quicklisp releases. In CI, on the one hand, we want to avoid moving parts so that the builds are more stable and reproducible, on the other hand, results for latest lisp implementation versions and latest quicklisp are the most interesting. 

One think currently missing with use of the Travis CI + roswell is that CLISP fails to install. But currently I don't see CLISP between your images.

Another project where Docker images may be useful is cl-test-grid. Crrently, Erik Huelsmann is hosting a server for cl-test-grid tests, but he needs those resorces for common-lisp.net so it's desirable for me to find another hosting. I was thinking to prepare a docker image for that, and when new Quicklisp is released, run that container on some of the cloud providers (probably multiple instances simultaneously), and after all tests are done the container would shut it down automatically, to stop consuming the resources. In my imagination that docker image would include all the implementations at once. Maybe an imapge per lisp implementation would be equally convenient. Or maybe not.

**Comment by daewok** [comment]
> Still, I'd be interesting to discuss how could that work, in particular regarding keeping up to date with latest lisp implementations and Quicklisp releases.

There are a variety of tags for each image. The `latest` tag is kept up to date with the latest version of each implementation, I typically have them built within a couple days of a new release. Additionally, there are tags for every version that is released. So if you want to use a consistent version in CI, just specify an image such as `clfoundation/sbcl:2.1.1`. One thing to note about the tags is that they are subject to Docker Hub's retention policy. So if no one pushes or pulls a tag in over 6 months, it is removed. There might be ways around that though if it's a true show stopper.

Additionally, I build nightly tags for several of the implementations. But building those is a real toll on the build infrastructure (especially SBCL) so I've paused adding that feature to all implementations for the moment. I'd like to find a compelling use case for them before continuing. I also suspect that a compelling use case does not really need nightly builds, and just release candidates would be sufficient.

Given the way the Quicklisp install works, the best way to keep it up to date is to not distribute it in the image. Every implementation specific image has an `install-quicklisp` shell script that performs the install. It defaults to installing the latest client and dist version, but those can both be overridden by environment variables.

> One thing currently missing with the use of the Travis CI + roswell is that CLISP fails to install. But currently I don't see CLISP between your images.

I was actually working on CLISP images yesterday with the goal of adding them to ASDF's CI. I just created the repos for them and they're currently building. It's v2.49.92 which was never "officially" released, but was tagged in the git repo, doesn't require patches to build on recent OSes, and seems to be what Debian and Ubuntu are distributing in their package managers. Why can't we get an actual release that's less than 10 years old?? :sob: 

> Another project where Docker images may be useful is cl-test-grid.

Yeah, someone (it might have been Erik, can't recall) suggested that the Docker images could be useful for cl-test-grid. I forgot to follow up on it, though!

> In my imagination that docker image would include all the implementations at once.

I'm happy to point you to the [`clfoundation/cl-devel`](https://hub.docker.com/r/clfoundation/cl-devel/) image. Its goal is to be a kitchen sink image that includes many implementations, has Quicklisp already installed, and has all foreign libs needed to load any system in Quicklisp (I'm sure there's probably a couple missing, though). I update it whenever a new Quicklisp dist or implementation version is released. 

The only thing missing from it at the moment is cmucl. That's because I haven't had the time yet to find the packages that install the 32-bit variants of all the foreign libs yet.
