### ISSUE TITLE
Wishlist: support kTLS

### ISSUE THREAD

**Issue by phmarek** [cl-plus-ssl/cl-plus-ssl#153]
This would greatly reduce the amount of work needed in userspace, allowing for better thread scheduling.

https://docs.kernel.org/networking/tls-offload.html, see also https://github.com/openssl/openssl/issues/14595.

**Comment by avodonosov** [comment]
From the openssl issue you linked, it seems kTLS will work out of the box for the file descriptor cl+ssl mode (`unwrap-stream-p t`).

Because cl+ssl uses SSL_set_fd, which installs socket BIO (https://www.openssl.org/docs/manmaster/man3/SSL_set_fd.html). And socket BIO gets kTLS automatically, according to the linked issue.

Do you see anything to be done on the cl+ssl side?

**Comment by avodonosov** [comment]
Can be closed I think.
