### ISSUE TITLE
eof detection on openssl 3

### ISSUE THREAD

**Issue by stassats** [cl-plus-ssl/cl-plus-ssl#166]
(drakma:http-request "https://google.com/" :additional-headers '(("Accept-Encoding" . "gzip")) :decode-content t) no longer works.
$return code: 1). ERR_print_errors(): 40F66EEE417F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:308:

ssl_read used to fail with +ssl-error-syscall+, which was then translated to ssl-error-zero-return, but now it fails with +ssl-error-ssl+.
Reading https://github.com/openssl/openssl/pull/10882 and all the associated issues doesn't provide any enlightenment, except that the error probably can't be ignored.

**Comment by avodonosov** [comment]
Why does EOF happen at all? Normally, HTTP client reads only as much data as server provides. Client determines that either by Content-Length or by chunked encoding.

**Comment by avodonosov** [comment]
I have reproduced this. Don't yet understand what's going on, but I discovered that if we switch cl+ssl to the Lisp BIO mode, 
by applying this https://github.com/edicl/drakma/pull/120 and then
```common-lisp
(setq cl+ssl:*default-unwrap-stream-p* nil)
```
The request works fine.

**Comment by stassats** [comment]
That's not important for the cl+ssl issue, since it does try to catch EOFs but fails to do so. (Or it shouldn't try at all)

**Comment by stassats** [comment]
But the reason drakma uses EOF is because it has twenty five different stream layers upon stream layers which don't communicate with each other.

**Comment by avodonosov** [comment]
Analyzing further, I came to opinion that cl+ssl should not suppress the "Unexpected EOF" error.

First, this may even open a possibility for some TLS truncation attack.

Second, HTTP client should not read past the last chunk of chunked encoding. If there were no OpenSSL layer, and the server didn't close the stream, the attempt to read the synchronous stream after all data is consumed would simply hand forever. I observed exactly this when set the `SSL_OP_IGNORE_UNEXPECTED_EOF ` option on the OpenSSL context that cl+ssl creates and running the code from description.

The problem is caused by the `chipz:decompressing-stream`. Note first, that `cl:read-sequence` signals EOF simply by reading smaller number of bytes than requested. The chipz library think this can be exercised several times. In this loop - https://github.com/sharplispers/chipz/blob/82a17d39c78d91f6ea63a03aca8f9aa6069a5e11/stream.lisp#L191 - it can refill part of its input buffer, and then on next iteration try to refill the buffer again. The loop is exited only when `cl:read-sequence` for the underlying stream returned exactly zero bytes. That second attempt for `cl:read-sequence` causes the unexpected EOF.

The following patch to chipz fixes the use case from the issue description:

```diff
diff --git a/stream.lisp b/stream.lisp
index 9b553f7..847686c 100644
--- a/stream.lisp
+++ b/stream.lisp
@@ -93,6 +93,7 @@
                  :reader input-buffer)
    (input-buffer-index :initform 0 :accessor input-buffer-index)
    (input-buffer-n-bytes :initform 0 :accessor input-buffer-n-bytes)
+   (input-eof-reached-p :initform nil :accessor input-eof-reached-p)
    (output-buffer :initform (make-array 4096 :element-type '(unsigned-byte 8))
                   :reader output-buffer)
    (output-buffer-index :initform 0 :accessor output-buffer-index)
@@ -122,10 +123,12 @@
 
 (defun refill-stream-input-buffer (stream)
   (with-slots (input-buffer wrapped-stream
-                            input-buffer-index input-buffer-n-bytes)
+                            input-buffer-index input-buffer-n-bytes
+               input-eof-reached-p)
       stream
     (let ((n-bytes-read (read-sequence input-buffer wrapped-stream)))
-      (setf input-buffer-index 0 input-buffer-n-bytes n-bytes-read)
+      (setf input-buffer-index 0 input-buffer-n-bytes n-bytes-read
+            input-eof-reached-p (< input-buffer-n-bytes (length input-buffer)))
       #+nil
       (format *trace-output* "index: ~D | n-bytes ~D~%"
               input-buffer-index input-buffer-n-bytes)
@@ -188,7 +191,8 @@
                     (setf start (copy-existing-output stream seq
                                                       start end)))
      while (< start end)
-     do (unless (input-available-p stream)
+     do (unless (or (input-available-p stream)
+                    (input-eof-reached-p stream))
           (refill-stream-input-buffer stream))
        ;; If we didn't refill, then we must be all done.
        (unless (input-available-p stream)
```

Similar logic change has to be done for `chipz:read-and-decompress-byte`.

**Comment by avodonosov** [comment]
Speaking of the difference between our custom Lisp BIO and the default OpenSSL's socket file descriptor BIO, I think we should adjust Lisp BIO so that the unexpected EOF is signaled too. I guess that should be done by setting the BIO_FLAGS_IN_EOF similar to https://github.com/openssl/openssl/pull/10882/files#diff-4b80c00c81d9bb3d8da74718ff3faf93f7e714adf83bca5bdf135c515cb0894bR127, instead of just doing nothing here: https://github.com/cl-plus-ssl/cl-plus-ssl/blob/7428577af51a8d3955e031420be0fe1a12cbdff3/src/bio.lisp#L220

Should the cl+ssl behavior for the old OpenSSL be changed to signal the unexpected EOF as error? I don't know yet. At least, with every day passing this question becomes less and less important.

**Comment by stassats** [comment]
That's my analysis as well, although my plan for fixing it is to emulate EOF on chunked streams in chunga, so that chipz and any other stream layer can continue looking for EOF repeatedly.

**Comment by avodonosov** [comment]
@stassats, I was looking into chunga too,  but seem more complex to me. Maybe just because I haven't studied it enough. My considerations:

Since the chunga public API guarantees to disable chunking after the last chunk is read, and allows further read without chunking, to avoid compatibility breakages such new behavior should be implemented as a non default, optional mode. 

>  Note that input chunking will usally be turned off automatically when the last chunk is read. 

https://edicl.github.io/chunga/

Introducing new option may increase complexity.


Also I see chunga tries to read http headers after the last chunk:
https://github.com/edicl/chunga/blob/783660961e3aabdc0e6b777763f7e1fab6036f72/input.lisp#L137

I don't know if that involves actual reading of the underlying stream, or that only processes already buffered data.

**Comment by stassats** [comment]
I solved it with https://github.com/edicl/chunga/commit/e7dc5365db9ebdd9368a87dcf66c0df7e35ba79a and https://github.com/edicl/drakma/commit/88b05e0c54ee65e45bcb687f67aede42918c5a6b

**Comment by avodonosov** [comment]
Strange that the `SSL_R_UNEXPECTED_EOF_WHILE_READING` is documented in OpenSSL docs as a situation where the remote peer has closed the TCP connection without sending TLS close alert. And the docs say this behavior is a violation of the TLS standard.

Does google really violate the standard? Or something else happens?

**Comment by avodonosov** [comment]
It seems the absence of a close_notify alert is not a problem for HTTP 1.1, if believe this answer: https://security.stackexchange.com/a/82044/282626

It explains, that in self-terminating protocols, where each party knows how many bytes to read from stream, such as HTTP 1.1 based on Content-Length or chunked encoding, the parties anyway know if part of request or response is missing, so SSL truncation don't change anything. And may web servers, including google.com, utilize this.

At the beginning of that security.stackexchange.com thread the author says oracle.com does send close_notify alert, while google does not.

I've tried our test case:
```common-lisp
(drakma:http-request "https://oracle.com/" :additional-headers '(("Accept-Encoding" . "gzip")) :decode-content t)
```  
and runs without the failure.

Adding tracing like below, I found that with google.com the "ssl-error-zero-return" is not logged, while for oracle.com it is logged. The testing was with openssl-3.0.4, so that's a real SSL_ERROR_ZERO_RETURN (not the substitution we do with old libssl when `ssl-error-zero-return` is signalled in case of `SLL_ERROR_SYSCALL, ret = 0` )
 
```diff
diff --git a/src/streams.lisp b/src/streams.lisp
index 0c8acdb..d53799c 100644
--- a/src/streams.lisp
+++ b/src/streams.lisp
@@ -111,6 +111,7 @@
               (and (> n 0) (buffer-elt buf 0))))))
 
 (defmethod stream-read-byte ((stream ssl-stream))
+  (format t "stream-read-byte~%")
   (or (prog1
           (ssl-stream-peeked-byte stream)
         (setf (ssl-stream-peeked-byte stream) nil))
@@ -122,9 +123,11 @@
                stream handle #'ssl-read handle ptr 1))
             (buffer-elt buf 0))
         (ssl-error-zero-return ()     ;SSL_read returns 0 on end-of-file
+          (format t "ssl-error-zero-return~%")
           :eof))))
 
 (defmethod stream-read-sequence ((stream ssl-stream) seq start end &key)
+  (format t "stream-read-sequence~%")
   (when (and (< start end) (ssl-stream-peeked-byte stream))
     (setf (elt seq start) (ssl-stream-peeked-byte stream))
     (setf (ssl-stream-peeked-byte stream) nil)
@@ -143,6 +146,7 @@
                (s/b-replace seq buf :start1 start :end1 (+ start read-bytes))
                (incf start read-bytes))
            (ssl-error-zero-return ()   ;SSL_read returns 0 on end-of-file
+             (format t "ssl-error-zero-return~%")
              (return))))
     ;; fixme: kein out-of-file wenn (zerop start)?
     start))
```

**Comment by avodonosov** [comment]
I decided to keep the suppression of Unexpected EOF errors on OpenSSL versions < 3.0, at leas for the time being. Added a comment in the code.

**Comment by reflektoin** [comment]
I ran into a similar error as the original poster. I tried binding `cl+ssl:*default-unwrap-stream-p*` to nil in the code below but that didn't help. Any pointers to give how to handle similar error message as in the original post? 

I tried with trivial-download and with drakma.

Trivial-download version:

```
(let ((cl+ssl:*default-unwrap-stream-p* nil))
(trivial-download:download 
 "https://stakohaavoindata.azurewebsites.net/avoindata/Espoo_kaupungin_ostolaskut__2012.xlsx" 
 "espoo_ostot_2012.xlsx"))

```

Drakma version. The code below depends also on [arnesi](https://quickdocs.org/arnesi):

```
(with-open-file (file "espoo_ostot_2012.xlsx"
                      :direction :output
                      :if-does-not-exist :create
                      :if-exists :supersede
                      :element-type '(unsigned-byte 8))
(let ((cl+ssl:*default-unwrap-stream-p* t))
  (let ((input (drakma:http-request "https://stakohaavoindata.azurewebsites.net/avoindata/Espoo_kaupungin_ostolaskut__2012.xlsx"
                                    :want-stream t)))
    (arnesi:awhile (read-byte input nil nil)
      (write-byte arnesi:it file))
    (close input))))
```

**Comment by avodonosov** [comment]
Probably you are on some old quicklisp? This has been fixed through chunga commit a year ago: https://github.com/cl-plus-ssl/cl-plus-ssl/issues/166#issuecomment-1238396837

**Comment by stassats** [comment]
I guess it hasn't been released yet.

**Comment by reflektoin** [comment]
Thanks for the quick responses! I'm now on new versions[1]. The expression from original post
```
(drakma:http-request "https://google.com/" :additional-headers '(("Accept-Encoding" . "gzip")) :decode-content t)
```

evaluates without problems, but my own code [2] still runs into the error 

`A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X7F8F1C14DA30) (SSL_get_error: 1). ERR_print_errors(): 40F6C61A8F7F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:`.


[1] 
```
CL-USER> (defun system-version (system-designator)
  (let ((system (asdf:find-system system-designator nil)))
    (when (and system (slot-boundp system 'asdf:version))
      (asdf:component-version system))))
SYSTEM-VERSION
CL-USER> (system-version :chunga)
"1.1.8"
CL-USER> (system-version :drakma)
"2.0.10"
CL-USER> (lisp-implementation-version)
"2.3.9"


```

[2]
```
(with-open-file (file "espoo_ostot_2012.xlsx"
                      :direction :output
                      :if-does-not-exist :create
                      :if-exists :supersede
                      :element-type '(unsigned-byte 8))
(let ((cl+ssl:*default-unwrap-stream-p* nil))
  (let ((input (drakma:http-request "https://stakohaavoindata.azurewebsites.net/avoindata/Espoo_kaupungin_ostolaskut__2012.xlsx"
                                    :want-stream t)))
    (arnesi:awhile (read-byte input nil nil)
      (write-byte arnesi:it file))
    (close input))))
```

**Comment by avodonosov** [comment]
@reflektoin, new drakma and chunga releases were just made by @stassats. See the repos. Dry with the new versions

**Comment by stassats** [comment]
The versions above are the new ones.

**Comment by avodonosov** [comment]
I have reproduced the error. The failing code also fails with openssl-1.1.1p, although  the error text is little different: "An I/O error occurred: undocumented reason (SSL_get_error: 5). ERR_print_errors():"

I think the problem is that the code really tries to read beyond the end of stream.

The server sends the content without gzipping and chunking.

When setting `(setq drakma:*header-stream* *standard-output*)` before executing the code, the following headers are printed:

```
GET /avoindata/Espoo_kaupungin_ostolaskut__2012.xlsx HTTP/1.1
Host: stakohaavoindata.azurewebsites.net
User-Agent: Drakma/2.0.10 (Clozure Common Lisp Version 1.12.1 (v1.12.1) LinuxX8664; Linux; 5.15.0-84-generic; http://weitz.de/drakma/)
Accept: */*
Connection: close

HTTP/1.1 200 OK
Content-Length: 27085896
Connection: close
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Date: Sun, 01 Oct 2023 11:40:56 GMT
Server: nginx/1.25.2
Accept-Ranges: bytes
ETag: "6125ec8c-19d4c48"
Last-Modified: Wed, 25 Aug 2021 07:09:00 GMT
Set-Cookie: ARRAffinity=7fd589394361d966a37b2319456f20a1c209fe5f93b9f5b91b4c0a564fe9035f;Path=/;HttpOnly;Secure;Domain=stakohaavoindata.azurewebsites.net
Set-Cookie: ARRAffinitySameSite=7fd589394361d966a37b2319456f20a1c209fe5f93b9f5b91b4c0a564fe9035f;Path=/;HttpOnly;SameSite=None;Secure;Domain=stakohaavoindata.azurewebsites.net

```

So the issues discussed in this ticket a year ago are not relevant.

I am not sure how drakma recommends to read data from binary stream returned when `:want-stream t`. I guess, when Content-Length header is present the user should only read this number of bytes. Otherwise, assume chunked encoding (or explicitly see if chunked is present in the Transfer-Encoding response header), which is handled by the stream returned automatically, and read till EOF, as the code does currently.

**Comment by reflektoin** [comment]
Thanks for the tips, I now got a working version, which is shown below. Any critiques and improvement suggestions are welcome.

```
(with-open-file (file "espoo_ostot_2012_.xlsx"
                      :direction :output
                      :if-does-not-exist :create
                      :if-exists :supersede
                      :element-type '(unsigned-byte 8))
  (let ((arvo nil)
        (content-length))
(multiple-value-bind (input status headers) (drakma:http-request "https://stakohaavoindata.azurewebsites.net/avoindata/Espoo_kaupungin_ostolaskut__2012.xlsx"
                                    :want-stream t)
  (setf content-length (parse-integer (cdr (assoc :content-length headers))))
    (dotimes (x content-length) 
      (setf arvo (read-byte input nil nil))
      (write-byte arvo file))
    (close input))))
```

**Comment by avodonosov** [comment]
@reflektoin, your code will work for this specific web server behaviour. If general code is needed, working for any web server, more generic approach is needed, accounting for all possible behaviours.

It's better to discuss in a separate drakma issue how to read from stream.

Here I will only explain the nuances related cl+ssl.

When you try switching to LispBIO by `(setq cl+ssl:*default-unwrap-stream-p* nil)` and it does not help, it's because when this issue was reported, the LispBIO was not correctly reporting EOF to the calling code, so the "unexpected EOR" error didn't happen. I have now [fixed](https://github.com/cl-plus-ssl/cl-plus-ssl/issues/166#ref-commit-cd16984) it, so the both LispBIO and socket BIO work equally.

Why the unexpected EOF happens at all, and why not always: the approach of readying stream until EOF works for code [3] and doesn't work for code [2] in your [comment](https://github.com/cl-plus-ssl/cl-plus-ssl/issues/166#issuecomment-1741777194).

TLS specification requires communicating parties (in our case web server) to send special close_alert before closing the stream. This is required to prevent TCP truncation attacks, where a malicious middle-man could inject TCP FIN packet in the middle of the body. The FIN packet is not encrypted, so the client who simply relies on TCP connection closure would think he received a complete authoritative response. For example, the client will think his logout request is successful, although the middle-man blocked it. Search online for more info on TCP truncation attacks.

OpenSSL reports "unexpected EOF" if connection is closed without close_alert (although cl+ssl suppressed it for old OpenSSL versions, for new versions the error is signalled).

However, some web servers, including google.com and your stakohaavoindata.azurewebsites.net, do not send close_alert, and simply close TCP connection. That's a performance optimization, without security risk, because since HTTP 1.1 the client knows the body size: either by the Content-Length response header or by chunked encoding (when body consists of a series of length prefixed chunks). The client is expected as many bytes as HTTP protocol guides him, and not rely on connection termination.

So, for servers who send close_notify alert, the simple approach of reading till EOF works - OpenSSl is happy. For servers who don't send close_notify, the error is signaled, as OpenSSL can't guarantee the response integrity.

**Comment by avodonosov** [comment]
I am writing a drakma issue: https://github.com/edicl/drakma/issues/138
