### ISSUE TITLE
[question] ssl-stream closes provided handle

### ISSUE THREAD

**Issue by dkochmanski** [cl-plus-ssl/cl-plus-ssl#39]
When `ssl-stream` is created and `make-ssl-client-stream` takes a file descriptor (like in Drakma case) as its first argument, its `close` method calls `close-socket` (on POSIX that leads to call of C function "close").

Since `close-callback` is set to the closure calling `close` on the original stream, we call C function "close" once again what leads to "Bad file descriptor" condition.

My question is whenever ssl-stream `close` method should close the socket if it's a descriptor (`integerp` `cond` branch in close method).

Another one is that if its OK to pass a flexi-stream as a socket to `make-ssl-client-stream`? If yes, then I'll make a pull request on `drakma` to pass a stream instead of `(cl+ssl:stream-fd s)` as the first argument. This seems to work.

I'll also harden ECL's close to avoid crash from the issue linked below (linked for context).

For the underlying issue see: https://gitlab.com/embeddable-common-lisp/ecl/issues/267#note_19385251/267#note_19385251

**Comment by avodonosov** [comment]
cc @deadtrickster 

1) Closing the file descriptor was implemented in the scope of #20. Now revisiting this I think it might be a wrong solution, because our docs [say] (https://common-lisp.net/project/cl-plus-ssl/): "If fd-or-stream is a lisp stream, the SSL stream will close it automatically. File descriptors are not closed automatically."

2) Passing a flexi-stream will enable cl+ssl's Lisp BIO (BIO is a stream-like abstraction in OpenSSL, We provide a CL-implemented BIO to OpenSSL and it calls us to read / write bytes). As far as I remember LispBIO remains buggy for years and no-one fixed that.

**Comment by deadtrickster** [comment]
I never had double-closing issue with drakma on SBCL. I added explicit close because drakma (or a lib around it) was leaking FDs.

**Comment by avodonosov** [comment]
@deadtrickster drakma passes close-callback to cl+ssl, and the callback closes the underlying stream: https://github.com/edicl/drakma/blob/master/util.lisp#L342

Therefore drakma shouldn't be leaking. Probably you experienced the leak with some other software?

**Comment by deadtrickster** [comment]
Probably. But it was like "add close here and leaks stop". Besides, why my drakma (or others, IIUC this propagated to QL already) doesn't complain on double close?

So maybe this error goes down to flexi streams or something like that. 

Ideally the one who opens should be closing of course.

**Comment by dkochmanski** [comment]
I don't know about other implementations, but in case of ECL ANSI streams with file descriptors if not closed by a programmer are taken care of during GC in the finalization code.

@deadtrickster If 3rd party software leaks file descriptors, I think this should be fixed there, not in `cl+ssl`.

@avodonosov are BIO bugs summarized anywhere?

**Comment by dkochmanski** [comment]
> Besides, why my drakma (or others, IIUC this propagated to QL already) doesn't complain on double close?

This is probably because drakma wraps `close` on stream in `ignore-errors`. I've noticed the error because of the crash in a stream finalizer.

**Comment by avodonosov** [comment]
> are LispBIO bugs summarized anywhere?

It was discussed in the mailing list threads years ago, I think when they were adding file descriptor support.

Even if LispBIO was correct, it is likely to have a performance penalty comparing to passing file descriptor to OpenSSL. 

BTW, flexi-stream is used to decode characters from bytes. SSL should wrap raw bytes. I mean if we wrap a lisp stream instead of file descriptor, in case of drakma the wrapping will be (flex-stream (ssl-stream socket-stream)). So you probably meant just socket stream, not flexi-stream.

**Comment by dkochmanski** [comment]
> BTW, flexi-stream is used to decode characters from bytes. SSL should wrap raw bytes. I mean if we wrap a lisp stream instead of file descriptor, in case of drakma the wrapping will be (flex-stream (ssl-stream socket-stream)). So you probably meant just socket stream, not flexi-stream.

Correct.

**Comment by deadtrickster** [comment]
@dkochmanski that's what I'm saying. 
Perhaps it was too bold and wrong place to fix anyway. But my production system was crashing and this worked.

**Comment by dkochmanski** [comment]
Sure, I totally understand

**Comment by avodonosov** [comment]
@dkochmanski one of the mentions of LispBIO problems (without details): https://mailman.common-lisp.net/pipermail/cl-plus-ssl-devel/2009-January/000088.html

**Comment by avodonosov** [comment]
I'm going to return the old functionality. @deadtrickster you might need to find the place you had the leak to fix it via `close-callback` (unless you're using a forked version)
