### ISSUE TITLE
OpenBSD 6.4 OPENSSL_sk_num undefined

### ISSUE THREAD

**Issue by iarebatman** [cl-plus-ssl/cl-plus-ssl#78]
This is my first attempt at doing anything with common lisp, so please forgive me for references dexador instead of finding a way to replicate this with only cl-plus-ssl.

Below is a very short sbcl session in which I try to do an https request to google.com.
I checked dexador's asdf file and it appears to depend on cl-plus-ssl, so I believe this bug belongs here.

Is there any additional information I can provide that would be helpful?

```
user$ sbcl
This is SBCL 1.4.8.openbsd, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :dexador)
To load "dexador":
  Load 1 ASDF system:
    dexador
; Loading "dexador"
......
(:DEXADOR)
* (dex:get "https://google.com")

debugger invoked on a SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR:
  The alien function "OPENSSL_sk_num" is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY-REQUEST] Retry the same request.
  1: [ABORT        ] Exit debugger, returning to top level.

("undefined function")
0] 
```

**Comment by avodonosov** [comment]
Hi, what version of quicklisp dist you use (see in the ~/quicklisp/dists/quicklisp/distinfo.txt file)? Please try (ql:update-all-dists) and restart SBCL so you will be on the latest version. I think it will work after that. Best regards,- Anton 18.04.2019, 22:38, "Brad DeMorrow" <notifications@github.com>:This is my first attempt at doing anything with common lisp, so please forgive me for references dexador instead of finding a way to replicate this with only cl-plus-ssl.Below is a very short sbcl session in which I try to do an https request to google.com.I checked dexador's asdf file and it appears to depend on cl-plus-ssl, so I believe this bug belongs here.Is there any additional information I can provide that would be helpful?user$ sbcl
This is SBCL 1.4.8.openbsd, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :dexador)
To load "dexador":
  Load 1 ASDF system:
    dexador
; Loading "dexador"
......
(:DEXADOR)
* (dex:get "https://google.com")

debugger invoked on a SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR:
  The alien function "OPENSSL_sk_num" is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY-REQUEST] Retry the same request.
  1: [ABORT        ] Exit debugger, returning to top level.

("undefined function")
0]

**Comment by iarebatman** [comment]
Here is the info you requested.  It appears that I'm already at the latest version.

```
name: quicklispsbcl 
This is SBCL 1.4.8.openbsd, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:update-all-dists)

1 dist to check.
You already have the latest version of "quicklisp": 2019-03-07.
NIL
```
```
cat ~/quicklisp/dists/quicklisp/distinfo.txt
version: 2019-03-07
system-index-url: http://beta.quicklisp.org/dist/quicklisp/2019-03-07/systems.txt
release-index-url: http://beta.quicklisp.org/dist/quicklisp/2019-03-07/releases.txt
archive-base-url: http://beta.quicklisp.org/
canonical-distinfo-url: http://beta.quicklisp.org/dist/quicklisp/2019-03-07/distinfo.txt
distinfo-subscription-url: http://beta.quicklisp.org/dist/quicklisp.txt
```

**Comment by iarebatman** [comment]
For the record, I don't appear to have a symbol named OPENSSL_sk_num in libcrypto or libssl on my machine.

```objdump -t /usr/lib/lib{crypto,ssl}.so.* | grep OPENSSL_sk_num```

returns 0 rows

**Comment by iarebatman** [comment]
Ok, quick update with a little more useful information.
Your compat-openssl-version function is returning 536870912 on my box (with LibreSSL 2.8.2 on it).

According to the LibreSSL (portable) homepage, they are compatible with OpenSSL 1.0.1 - but not 1.1 (https://github.com/libressl-portable/portable)

I modified your sk-general-name-value and sk-general-name-num function to simply return (sk-value names index) and (sk-num names), which allowed dexador to properly work with an https request..

I spent about an hour looking through the CFFI documentation for a way to check to see if there was a way I could check the openssl-sk-value and openssl-sk-num values to see if they were valid pointers to functions, but I came up empty so far.. Perhaps someone more familiar with the library would know the best way to do that?
I tried using (cffi:pointerp openssl-sk-value), but that doesn't seem to do what I thought it would.

Then again, perhaps the best approach would be to make your code check specifically for LibreSSL version(s) for compatibility?

**Comment by avodonosov** [comment]
How to check if this livres so and what version it us? Is there an API for that?

**Comment by iarebatman** [comment]
http://man.openbsd.org/OPENSSL_VERSION_NUMBER.3

**Comment by iarebatman** [comment]
Here is a pull request:
https://github.com/cl-plus-ssl/cl-plus-ssl/pull/79
